/* ============================================================
   無機化学 色図鑑データベース
   高校化学〜大学受験で覚えるべき「色」を全網羅
   ============================================================ */

// 色パレット（色名 → 表示色）
const PALETTE = {
  "赤":       "#e8382f",
  "赤(深赤)": "#c81e3c",   // Sr 紅色
  "赤紫":     "#b03a9e",
  "血赤":     "#8a0303",
  "暗赤":     "#7a1010",
  "橙赤":     "#ff5722",
  "赤橙":     "#ff6a13",
  "橙":       "#ff8c00",
  "黄":       "#f5c400",
  "淡黄":     "#f0e099",
  "黄褐":     "#b8860b",
  "黄緑":     "#9acd32",
  "緑":       "#2e8b57",
  "淡緑":     "#a8e6a1",
  "灰緑":     "#6b8e6b",
  "緑白":     "#cdeacd",
  "青緑":     "#00a99d",
  "青":       "#1e6fd9",
  "深青":     "#15279c",
  "濃青(紺青)": "#16226e",
  "淡青":     "#a5d8e6",
  "青白":     "#cfe4f5",
  "青紫":     "#4b3c9e",
  "紫":       "#7d3cb5",
  "黒紫":     "#2e0f3a",
  "淡赤(桃)": "#f4a7b9",
  "赤褐":     "#8b3a2a",
  "褐":       "#7b4a12",
  "黒":       "#15151a",
  "白":       "#f8f8f8",
  "銀白":     "#d8dde2",
  "金(黄金)": "#d4af37",
  "無色":     "#eef0f6",
};

// カテゴリ定義
const CATEGORIES = {
  flame:   { name: "炎色反応",        icon: "🔥" },
  ion:     { name: "イオンの色(水溶液)", icon: "💧" },
  precip:  { name: "沈殿の色",        icon: "🧪" },
  detect:  { name: "検出・呈色反応",   icon: "🔬" },
  gas:     { name: "気体の色",        icon: "💨" },
  solid:   { name: "単体・化合物(固体)", icon: "💎" },
  indicator:{ name: "指示薬の色",      icon: "🌡️" },
};

/*
  各項目: { q: 出題文(物質・反応), sub: 補足(化学式など), color: 色名, cat: カテゴリ, memo: 覚え方・補足 }
*/
const COLOR_DB = [
  // ========== 炎色反応 (リアカー無きK村…) ==========
  { q: "リチウムの炎色反応",     sub: "Li",  color: "赤",       cat: "flame", memo: "リアカー(Li赤)" },
  { q: "ナトリウムの炎色反応",   sub: "Na",  color: "黄",       cat: "flame", memo: "無き(Na黄)" },
  { q: "カリウムの炎色反応",     sub: "K",   color: "赤紫",     cat: "flame", memo: "K村(K紫)" },
  { q: "銅の炎色反応",           sub: "Cu",  color: "青緑",     cat: "flame", memo: "動力(Cu緑)" },
  { q: "カルシウムの炎色反応",   sub: "Ca",  color: "橙赤",     cat: "flame", memo: "借りると(Ca橙)" },
  { q: "ストロンチウムの炎色反応", sub: "Sr", color: "赤(深赤)", cat: "flame", memo: "するもくれない(Sr紅)" },
  { q: "バリウムの炎色反応",     sub: "Ba",  color: "黄緑",     cat: "flame", memo: "馬力(Ba黄緑)" },

  // ========== イオンの色（水溶液） ==========
  { q: "銅(II)イオンの水溶液",       sub: "Cu²⁺",  color: "青",       cat: "ion", memo: "CuSO₄水溶液の青" },
  { q: "鉄(II)イオンの水溶液",       sub: "Fe²⁺",  color: "淡緑",     cat: "ion", memo: "Fe²⁺は淡緑・Fe³⁺は黄褐で区別" },
  { q: "鉄(III)イオンの水溶液",      sub: "Fe³⁺",  color: "黄褐",     cat: "ion", memo: "" },
  { q: "ニッケル(II)イオンの水溶液", sub: "Ni²⁺",  color: "緑",       cat: "ion", memo: "" },
  { q: "クロム(III)イオンの水溶液",  sub: "Cr³⁺",  color: "緑",       cat: "ion", memo: "暗緑色" },
  { q: "マンガン(II)イオンの水溶液", sub: "Mn²⁺",  color: "淡赤(桃)", cat: "ion", memo: "ほぼ無色〜淡桃色" },
  { q: "コバルト(II)イオンの水溶液", sub: "Co²⁺",  color: "淡赤(桃)", cat: "ion", memo: "桃色" },
  { q: "過マンガン酸イオンの水溶液", sub: "MnO₄⁻", color: "赤紫",     cat: "ion", memo: "酸化剤の代表・赤紫" },
  { q: "クロム酸イオンの水溶液",     sub: "CrO₄²⁻", color: "黄",      cat: "ion", memo: "クロム酸=黄" },
  { q: "二クロム酸イオンの水溶液",   sub: "Cr₂O₇²⁻", color: "赤橙",   cat: "ion", memo: "二クロム酸=赤橙" },
  { q: "テトラアンミン銅(II)イオン", sub: "[Cu(NH₃)₄]²⁺", color: "深青", cat: "ion", memo: "Cu(OH)₂+過剰NH₃で深青" },
  { q: "ヘキサシアニド鉄(III)酸イオン", sub: "[Fe(CN)₆]³⁻", color: "黄", cat: "ion", memo: "" },
  { q: "ヘキサシアニド鉄(II)酸イオン",  sub: "[Fe(CN)₆]⁴⁻", color: "淡黄", cat: "ion", memo: "" },

  // ========== 沈殿の色 ==========
  { q: "塩化銀の沈殿",           sub: "AgCl",   color: "白",       cat: "precip", memo: "感光して黒くなる" },
  { q: "臭化銀の沈殿",           sub: "AgBr",   color: "淡黄",     cat: "precip", memo: "Cl白→Br淡黄→I黄と濃くなる" },
  { q: "ヨウ化銀の沈殿",         sub: "AgI",    color: "黄",       cat: "precip", memo: "" },
  { q: "クロム酸銀の沈殿",       sub: "Ag₂CrO₄", color: "暗赤",    cat: "precip", memo: "赤褐〜暗赤色" },
  { q: "酸化銀の沈殿",           sub: "Ag₂O",   color: "褐",       cat: "precip", memo: "Ag⁺+OH⁻→褐色Ag₂O" },
  { q: "硫化銀の沈殿",           sub: "Ag₂S",   color: "黒",       cat: "precip", memo: "" },
  { q: "硫酸バリウムの沈殿",     sub: "BaSO₄",  color: "白",       cat: "precip", memo: "X線造影剤" },
  { q: "硫酸カルシウムの沈殿",   sub: "CaSO₄",  color: "白",       cat: "precip", memo: "" },
  { q: "硫酸鉛(II)の沈殿",       sub: "PbSO₄",  color: "白",       cat: "precip", memo: "" },
  { q: "炭酸カルシウムの沈殿",   sub: "CaCO₃",  color: "白",       cat: "precip", memo: "石灰水の白濁" },
  { q: "炭酸バリウムの沈殿",     sub: "BaCO₃",  color: "白",       cat: "precip", memo: "" },
  { q: "塩化鉛(II)の沈殿",       sub: "PbCl₂",  color: "白",       cat: "precip", memo: "熱水に溶ける" },
  { q: "ヨウ化鉛(II)の沈殿",     sub: "PbI₂",   color: "黄",       cat: "precip", memo: "美しい黄色沈殿" },
  { q: "クロム酸鉛(II)の沈殿",   sub: "PbCrO₄", color: "黄",       cat: "precip", memo: "黄色顔料(クロムイエロー)" },
  { q: "クロム酸バリウムの沈殿", sub: "BaCrO₄", color: "黄",       cat: "precip", memo: "" },
  { q: "硫化銅(II)の沈殿",       sub: "CuS",    color: "黒",       cat: "precip", memo: "酸性でも沈殿" },
  { q: "硫化鉛(II)の沈殿",       sub: "PbS",    color: "黒",       cat: "precip", memo: "酸性でも沈殿" },
  { q: "硫化水銀(II)の沈殿",     sub: "HgS",    color: "黒",       cat: "precip", memo: "酸性でも沈殿" },
  { q: "硫化カドミウムの沈殿",   sub: "CdS",    color: "黄",       cat: "precip", memo: "黄色顔料(カドミウムイエロー)" },
  { q: "硫化スズ(II)の沈殿",     sub: "SnS",    color: "褐",       cat: "precip", memo: "褐色" },
  { q: "硫化亜鉛の沈殿",         sub: "ZnS",    color: "白",       cat: "precip", memo: "硫化物なのに白！頻出" },
  { q: "硫化マンガン(II)の沈殿", sub: "MnS",    color: "淡赤(桃)", cat: "precip", memo: "淡赤(淡桃)色" },
  { q: "硫化鉄(II)の沈殿",       sub: "FeS",    color: "黒",       cat: "precip", memo: "" },
  { q: "硫化ニッケル(II)の沈殿", sub: "NiS",    color: "黒",       cat: "precip", memo: "" },
  { q: "水酸化アルミニウムの沈殿", sub: "Al(OH)₃", color: "白",    cat: "precip", memo: "両性水酸化物" },
  { q: "水酸化亜鉛の沈殿",       sub: "Zn(OH)₂", color: "白",      cat: "precip", memo: "両性水酸化物" },
  { q: "水酸化マグネシウムの沈殿", sub: "Mg(OH)₂", color: "白",    cat: "precip", memo: "" },
  { q: "水酸化鉄(II)の沈殿",     sub: "Fe(OH)₂", color: "緑白",    cat: "precip", memo: "空気酸化で赤褐色へ" },
  { q: "水酸化鉄(III)の沈殿",    sub: "Fe(OH)₃ (酸化水酸化鉄)", color: "赤褐", cat: "precip", memo: "" },
  { q: "水酸化銅(II)の沈殿",     sub: "Cu(OH)₂", color: "青白",    cat: "precip", memo: "加熱するとCuO(黒)に" },
  { q: "水酸化クロム(III)の沈殿", sub: "Cr(OH)₃", color: "灰緑",   cat: "precip", memo: "" },

  // ========== 検出・呈色反応 ==========
  { q: "Fe³⁺ + ヘキサシアニド鉄(II)酸カリウム", sub: "紺青(プルシアンブルー)の生成", color: "濃青(紺青)", cat: "detect", memo: "Fe³⁺の検出" },
  { q: "Fe²⁺ + ヘキサシアニド鉄(III)酸カリウム", sub: "ターンブル青の生成", color: "濃青(紺青)", cat: "detect", memo: "Fe²⁺の検出" },
  { q: "Fe³⁺ + チオシアン酸カリウム(KSCN)", sub: "チオシアン酸鉄", color: "血赤", cat: "detect", memo: "Fe³⁺の検出・血赤色" },
  { q: "ヨウ素デンプン反応",       sub: "I₂ + デンプン",  color: "青紫", cat: "detect", memo: "ヨウ素の検出" },
  { q: "フェーリング液の還元(沈殿)", sub: "Cu₂O が生成",  color: "赤",   cat: "detect", memo: "還元糖・アルデヒドの検出" },
  { q: "銀鏡反応で析出する銀",     sub: "Ag",             color: "銀白", cat: "detect", memo: "アルデヒドの検出" },
  { q: "ビウレット反応",           sub: "タンパク質 + NaOH + CuSO₄", color: "赤紫", cat: "detect", memo: "ペプチド結合2つ以上" },
  { q: "キサントプロテイン反応",   sub: "タンパク質 + 濃硝酸", color: "黄", cat: "detect", memo: "ベンゼン環のニトロ化(冷後アンモニアで橙)" },
  { q: "ニンヒドリン反応",         sub: "アミノ基の検出",  color: "紫",   cat: "detect", memo: "赤紫〜青紫" },
  { q: "塩化コバルト紙(乾燥時)",   sub: "CoCl₂",          color: "青",   cat: "detect", memo: "水に触れると桃色に" },
  { q: "塩化コバルト紙(水で変色後)", sub: "水の検出",      color: "淡赤(桃)", cat: "detect", memo: "青→桃色" },
  { q: "酢酸鉛(II)紙の変色(硫黄検出)", sub: "PbSの生成",  color: "黒",   cat: "detect", memo: "S²⁻/H₂Sの検出" },

  // ========== 気体の色 ==========
  { q: "塩素(気体)",           sub: "Cl₂",  color: "黄緑", cat: "gas", memo: "刺激臭・漂白作用" },
  { q: "フッ素(気体)",         sub: "F₂",   color: "淡黄", cat: "gas", memo: "" },
  { q: "二酸化窒素",           sub: "NO₂",  color: "赤褐", cat: "gas", memo: "銅+濃硝酸で発生" },
  { q: "一酸化窒素",           sub: "NO",   color: "無色", cat: "gas", memo: "空気中で酸化されNO₂(赤褐)に" },
  { q: "オゾン",               sub: "O₃",   color: "淡青", cat: "gas", memo: "特異臭" },
  { q: "臭素の蒸気",           sub: "Br₂(気体)", color: "赤褐", cat: "gas", memo: "" },
  { q: "ヨウ素の蒸気",         sub: "I₂(気体)",  color: "紫",  cat: "gas", memo: "昇華性" },
  { q: "硫化水素(気体)",       sub: "H₂S",  color: "無色", cat: "gas", memo: "腐卵臭・無色" },
  { q: "アンモニア(気体)",     sub: "NH₃",  color: "無色", cat: "gas", memo: "刺激臭・無色" },

  // ========== 単体・化合物（固体） ==========
  { q: "臭素(液体)",             sub: "Br₂",  color: "赤褐", cat: "solid", memo: "常温で液体の非金属" },
  { q: "ヨウ素(固体)",           sub: "I₂",   color: "黒紫", cat: "solid", memo: "昇華性・金属光沢" },
  { q: "硫黄(固体)",             sub: "S",    color: "黄",   cat: "solid", memo: "斜方硫黄・単斜硫黄" },
  { q: "黄リン",                 sub: "P₄",   color: "淡黄", cat: "solid", memo: "自然発火・猛毒" },
  { q: "赤リン",                 sub: "P",    color: "赤褐", cat: "solid", memo: "マッチの側薬" },
  { q: "銅(金属)",               sub: "Cu",   color: "赤",   cat: "solid", memo: "赤色の金属光沢" },
  { q: "金(金属)",               sub: "Au",   color: "金(黄金)", cat: "solid", memo: "黄金色の光沢" },
  { q: "酸化銅(II)",             sub: "CuO",  color: "黒",   cat: "solid", memo: "銅を加熱(高温)" },
  { q: "酸化銅(I)",              sub: "Cu₂O", color: "赤",   cat: "solid", memo: "フェーリング反応の沈殿" },
  { q: "酸化鉄(III)",            sub: "Fe₂O₃", color: "赤褐", cat: "solid", memo: "赤さび・べんがら" },
  { q: "四酸化三鉄",             sub: "Fe₃O₄", color: "黒",  cat: "solid", memo: "黒さび・磁性" },
  { q: "酸化鉄(II)",             sub: "FeO",  color: "黒",   cat: "solid", memo: "" },
  { q: "酸化マンガン(IV)",       sub: "MnO₂", color: "黒",   cat: "solid", memo: "触媒・乾電池" },
  { q: "酸化亜鉛",               sub: "ZnO",  color: "白",   cat: "solid", memo: "白色顔料(亜鉛華)" },
  { q: "酸化アルミニウム",       sub: "Al₂O₃", color: "白",  cat: "solid", memo: "アルミナ・ルビーやサファイアの主成分" },
  { q: "過マンガン酸カリウム(固体)", sub: "KMnO₄", color: "黒紫", cat: "solid", memo: "水溶液は赤紫" },
  { q: "二クロム酸カリウム(固体)",   sub: "K₂Cr₂O₇", color: "赤橙", cat: "solid", memo: "" },
  { q: "硫酸銅(II)五水和物",     sub: "CuSO₄·5H₂O", color: "青", cat: "solid", memo: "加熱で白色無水物に" },
  { q: "硫酸銅(II)無水物",       sub: "CuSO₄", color: "白",  cat: "solid", memo: "水を吸うと青に→水の検出" },
  { q: "銅のさび(緑青)",         sub: "ろくしょう", color: "青緑", cat: "solid", memo: "銅像の表面の色" },

  // ========== 指示薬 ==========
  { q: "フェノールフタレイン(塩基性)", sub: "pH > 8.3", color: "赤",   cat: "indicator", memo: "酸性〜中性では無色" },
  { q: "フェノールフタレイン(酸性〜中性)", sub: "pH < 8.3", color: "無色", cat: "indicator", memo: "" },
  { q: "BTB溶液(酸性)",     sub: "ブロモチモールブルー", color: "黄", cat: "indicator", memo: "き(黄)み(緑)どりあお(青)" },
  { q: "BTB溶液(中性)",     sub: "ブロモチモールブルー", color: "緑", cat: "indicator", memo: "" },
  { q: "BTB溶液(塩基性)",   sub: "ブロモチモールブルー", color: "青", cat: "indicator", memo: "" },
  { q: "メチルオレンジ(酸性)",   sub: "pH < 3.1", color: "赤", cat: "indicator", memo: "変色域 3.1〜4.4" },
  { q: "メチルオレンジ(pH4.4以上)", sub: "中性〜塩基性", color: "黄", cat: "indicator", memo: "" },
  { q: "リトマス(酸性)",   sub: "青色リトマス紙の変色", color: "赤", cat: "indicator", memo: "" },
  { q: "リトマス(塩基性)", sub: "赤色リトマス紙の変色", color: "青", cat: "indicator", memo: "" },
];
